"""pipeline/metro_resolver.py - leaf service, pure, unit-testable.
Resolves visitor country (ISO-2) + optional city to an Equinix metro.
Reads data/metro_map.json (generated by scripts/extract_metro_map.py from the
IBX dataset). city->metro is precise; country->flagship is fallback.
If the map file is missing/unreadable, degrades to empty lookups (never crashes
search - matches the codebase's 'code fallbacks everywhere' posture)."""
import json
import os

_MAP_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "metro_map.json")

def _load_map():
    try:
        with open(os.path.normpath(_MAP_PATH)) as f:
            m = json.load(f)
        return (m.get("city_to_metro", {}) or {},
                m.get("country_flagship", {}) or {},
                m.get("metro_meta", {}) or {})
    except Exception:
        return {}, {}, {}

_CITY_TO_METRO, _COUNTRY_FLAGSHIP, _METRO_META = _load_map()


def resolve_metro(country="", city=""):
    """city -> metro (precise); country -> flagship metro (fallback).
    Pure lookups over the loaded map. Returns "" if neither resolves."""
    if city:
        m = _CITY_TO_METRO.get(city.strip().lower())
        if m:
            return m
    if country:
        return _COUNTRY_FLAGSHIP.get(country.strip().upper(), "")
    return ""


def metro_region(metro=""):
    """metro name -> AMER/EMEA/APAC, or "" if unknown."""
    info = _METRO_META.get(metro)
    return info.get("region", "") if info else ""


def metro_code(metro=""):
    """metro name -> IBX metro code (e.g. 'SV'), or "" if unknown."""
    info = _METRO_META.get(metro)
    return info.get("code", "") if info else ""
